name: Build and Deploy

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install 🔧
        run: npm ci

      - name: Lint 🔬
        run: npm run lint

      - name: Test 🧪
        run: npm run test

      - name: Build 🏗
        run: npm run build
        env:
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
          VITE_PROJECT_ID: ${{ secrets.VITE_PROJECT_ID }}
          VITE_DICTIONARY_DB_ID: ${{ secrets.VITE_DICTIONARY_DB_ID }}
          VITE_WORDS_COLLECTION_ID: ${{ secrets.VITE_WORDS_COLLECTION_ID }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
